<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>CardSurvival_Localization</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <FileVersion>4.0.0</FileVersion>
    <AssemblyVersion>4.0.0</AssemblyVersion>
    <Description></Description>
    <Title></Title>
    <Product>$(AssemblyName)</Product>
    <PackageReleaseNotes></PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="GameDefaultKeys.txt" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="GameDefaultKeys.txt" />
  </ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="CardSurvival-LocalizationTests" />
	</ItemGroup>

	<!--<Target Name="RemoveObjAndBin" AfterTargets="Clean">
		--><!-- common vars https://learn.microsoft.com/en-us/cpp/build/reference/common-macros-for-build-commands-and-properties?view=msvc-170 --><!--
		--><!-- bin --><!--
		<RemoveDir Directories="$(TargetDir)" />
		--><!-- obj --><!--
		<RemoveDir Directories="$(ProjectDir)$(BaseIntermediateOutputPath)" />
	</Target>-->
	
	<ItemGroup>
    <PackageReference Include="Cocona" Version="2.2.0" />
    <PackageReference Include="CsvHelper" Version="33.0.1" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="9.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Text.Json" Version="9.0.0" />
    <PackageReference Include="TestableIO.System.IO.Abstractions" Version="21.2.1" />
    <PackageReference Include="TestableIO.System.IO.Abstractions.Wrappers" Version="21.2.1" />
  </ItemGroup>

</Project>
